### Request user with ID
GET http://127.0.0.1:8000/user/1

### Request to user edit using POST
POST http://127.0.0.1:8000/user/1/edit

### Request to delete user with DELETE
DELETE http://127.0.0.1:8000/user/1/delete
